pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Nginx') {
      agent {
        docker { image 'nginxinc/nginx-unprivileged' }
      }
      steps {
        sh 'nginx -v'
      }
    } 
    stage('Gittu') {
      agent {
        docker { image 'bitnami/git' }
      }
      steps {
        sh 'bitnami/git --version'
      }
    }
  }
}
